import React, { useState, useEffect, useCallback } from "react";
import {
  View,
  Text,
  StyleSheet,
  FlatList,
  Pressable,
  Modal,
  ScrollView,
  ActivityIndicator,
  Alert,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import * as Haptics from "expo-haptics";
import Animated, { FadeInDown } from "react-native-reanimated";
import Colors from "@/constants/colors";
import { addAuditLog, getEmployees, getSalaries, updateSalaryStatus } from "@/lib/storage";
import type { SalaryRecord } from "@/lib/types";
import { useAppTheme } from "@/contexts/ThemeContext";
import { AppCanvas } from "@/components/AppCanvas";
import { useAuth } from "@/contexts/AuthContext";
import * as Crypto from "expo-crypto";
import * as Print from "expo-print";

function formatMonthLabel(monthKey: string): string {
  return new Date(`${monthKey}-01`).toLocaleDateString("en-US", {
    month: "long",
    year: "numeric",
  });
}

function formatCurrency(value: number): string {
  return `INR ${value.toLocaleString()}`;
}

function getSalarySlipNumber(salary: SalaryRecord): string {
  const monthPart = salary.month.replace("-", "");
  const employeePart = salary.employeeId.replace(/[^a-z0-9]/gi, "").slice(-6).toUpperCase() || "EMP";
  return `SLIP-${monthPart}-${employeePart}`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function buildSalarySlipHtml(input: {
  salary: SalaryRecord;
  companyName: string;
  generatedBy: string;
  generatedAtISO: string;
}): string {
  const monthLabel = formatMonthLabel(input.salary.month);
  const slipNumber = getSalarySlipNumber(input.salary);
  const row = (label: string, value: number, weight: "normal" | "bold" = "normal") =>
    `<tr><td style="padding:8px 0;color:#475569;font-weight:${weight};">${escapeHtml(label)}</td><td style="padding:8px 0;text-align:right;font-weight:${weight};">${escapeHtml(formatCurrency(value))}</td></tr>`;

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Salary Slip ${escapeHtml(monthLabel)}</title>
    <style>
      body { font-family: Arial, Helvetica, sans-serif; margin: 0; padding: 24px; color: #0f172a; }
      .card { border: 1px solid #e2e8f0; border-radius: 14px; padding: 18px 20px; }
      .top { display: flex; justify-content: space-between; gap: 16px; margin-bottom: 14px; }
      .muted { color: #64748b; font-size: 12px; }
      .title { font-size: 22px; font-weight: 700; margin: 0; }
      .chip { font-size: 12px; display: inline-block; padding: 4px 10px; border-radius: 999px; background: #ecfeff; color: #0f766e; font-weight: 700; text-transform: uppercase; letter-spacing: .3px; }
      table { width: 100%; border-collapse: collapse; }
      .section { margin-top: 18px; }
      .section h3 { margin: 0 0 8px; font-size: 13px; text-transform: uppercase; letter-spacing: .4px; color: #334155; }
      .net { border-top: 1px solid #e2e8f0; margin-top: 10px; padding-top: 10px; display:flex; justify-content: space-between; font-size: 17px; font-weight: 800; color: #047857; }
      .footer { margin-top: 14px; font-size: 11px; color: #94a3b8; }
    </style>
  </head>
  <body>
    <div class="card">
      <div class="top">
        <div>
          <div class="muted">Company</div>
          <h1 class="title">${escapeHtml(input.companyName)}</h1>
          <div style="margin-top:6px;font-size:13px;">Salary Slip - ${escapeHtml(monthLabel)}</div>
        </div>
        <div style="text-align:right;">
          <div class="chip">${escapeHtml(input.salary.status)}</div>
          <div style="margin-top:10px;" class="muted">Slip No: ${escapeHtml(slipNumber)}</div>
          <div class="muted">Employee: ${escapeHtml(input.salary.employeeName)}</div>
          <div class="muted">Generated by: ${escapeHtml(input.generatedBy)}</div>
          <div class="muted">Generated on: ${escapeHtml(new Date(input.generatedAtISO).toLocaleString())}</div>
        </div>
      </div>

      <div class="section">
        <h3>Earnings</h3>
        <table>
          ${row("Basic", input.salary.basic)}
          ${row("HRA", input.salary.hra)}
          ${row("Transport", input.salary.transport)}
          ${row("Medical", input.salary.medical)}
          ${row("Bonus", input.salary.bonus)}
          ${row("Overtime", input.salary.overtime)}
          ${row("Gross Pay", input.salary.grossPay, "bold")}
        </table>
      </div>

      <div class="section">
        <h3>Deductions</h3>
        <table>
          ${row("Income Tax", input.salary.tax)}
          ${row("Provident Fund", input.salary.pf)}
          ${row("Insurance", input.salary.insurance)}
          ${row("Total Deductions", input.salary.totalDeductions, "bold")}
        </table>
      </div>

      <div class="net">
        <span>Net Pay</span>
        <span>${escapeHtml(formatCurrency(input.salary.netPay))}</span>
      </div>
      <div class="footer">This is a system-generated salary slip.</div>
    </div>
  </body>
</html>`;
}

function SalaryBreakdown({
  salary,
  colors,
  isAdmin,
  onMarkPaid,
  onViewSlip,
  onPrintSlip,
  printingSlipId,
}: {
  salary: SalaryRecord;
  colors: typeof Colors.light;
  isAdmin: boolean;
  onMarkPaid: (salaryId: string) => void;
  onViewSlip: (salary: SalaryRecord) => void;
  onPrintSlip: (salary: SalaryRecord) => void;
  printingSlipId: string | null;
}) {
  const [expanded, setExpanded] = useState(false);
  const statusColor =
    salary.status === "paid" ? colors.success :
    salary.status === "approved" ? colors.primary : colors.warning;
  const isPrinting = printingSlipId === salary.id;

  return (
    <Pressable
      onPress={() => {
        Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
        setExpanded(!expanded);
      }}
      style={[styles.salaryCard, { backgroundColor: colors.backgroundElevated, borderColor: colors.border }]}
    >
      <View style={styles.salaryHeader}>
        <View style={styles.salaryHeaderLeft}>
          <Text style={[styles.salaryName, { color: colors.text, fontFamily: "Inter_600SemiBold" }]}>
            {salary.employeeName}
          </Text>
          <Text style={[styles.salaryMonth, { color: colors.textSecondary, fontFamily: "Inter_400Regular" }]}>
            {formatMonthLabel(salary.month)}
          </Text>
        </View>
        <View style={styles.salaryHeaderRight}>
          <Text style={[styles.netPay, { color: colors.text, fontFamily: "Inter_700Bold" }]}>
            {formatCurrency(salary.netPay)}
          </Text>
          <View style={[styles.statusChip, { backgroundColor: statusColor + "15" }]}>
            <Text style={[styles.statusText, { color: statusColor, fontFamily: "Inter_500Medium" }]}>
              {salary.status}
            </Text>
          </View>
        </View>
      </View>

      {expanded && (
        <Animated.View entering={FadeInDown.duration(300)} style={styles.breakdown}>
          <View style={[styles.breakdownDivider, { backgroundColor: colors.border }]} />
          <Text style={[styles.breakdownSection, { color: colors.success, fontFamily: "Inter_600SemiBold" }]}>
            Earnings
          </Text>
          <BreakdownRow label="Basic" value={salary.basic} colors={colors} />
          <BreakdownRow label="HRA" value={salary.hra} colors={colors} />
          <BreakdownRow label="Transport" value={salary.transport} colors={colors} />
          <BreakdownRow label="Medical" value={salary.medical} colors={colors} />
          <BreakdownRow label="Bonus" value={salary.bonus} colors={colors} />
          <BreakdownRow label="Overtime" value={salary.overtime} colors={colors} />
          <BreakdownRow label="Gross Pay" value={salary.grossPay} colors={colors} bold />

          <Text style={[styles.breakdownSection, { color: colors.danger, fontFamily: "Inter_600SemiBold", marginTop: 12 }]}>
            Deductions
          </Text>
          <BreakdownRow label="Income Tax" value={salary.tax} colors={colors} />
          <BreakdownRow label="Provident Fund" value={salary.pf} colors={colors} />
          <BreakdownRow label="Insurance" value={salary.insurance} colors={colors} />
          <BreakdownRow label="Total Deductions" value={salary.totalDeductions} colors={colors} bold />

          <View style={[styles.netPayRow, { borderTopColor: colors.border }]}>
            <Text style={[styles.netPayLabel, { color: colors.text, fontFamily: "Inter_700Bold" }]}>Net Pay</Text>
            <Text style={[styles.netPayValue, { color: colors.success, fontFamily: "Inter_700Bold" }]}>
              {formatCurrency(salary.netPay)}
            </Text>
          </View>

          <View style={styles.actionRow}>
            <Pressable
              onPress={() => onViewSlip(salary)}
              style={({ pressed }) => [
                styles.secondaryActionButton,
                {
                  borderColor: colors.border,
                  backgroundColor: colors.surface,
                  opacity: pressed ? 0.86 : 1,
                },
              ]}
            >
              <Ionicons name="document-text-outline" size={15} color={colors.textSecondary} />
              <Text style={[styles.secondaryActionButtonText, { color: colors.textSecondary }]}>
                View Slip
              </Text>
            </Pressable>

            <Pressable
              onPress={() => onPrintSlip(salary)}
              disabled={isPrinting}
              style={({ pressed }) => [
                styles.secondaryActionButton,
                {
                  borderColor: colors.primary,
                  backgroundColor: colors.primary + "12",
                  opacity: pressed || isPrinting ? 0.8 : 1,
                },
              ]}
            >
              {isPrinting ? (
                <ActivityIndicator size="small" color={colors.primary} />
              ) : (
                <Ionicons name="print-outline" size={15} color={colors.primary} />
              )}
              <Text style={[styles.secondaryActionButtonText, { color: colors.primary }]}>
                {isPrinting ? "Printing..." : "Print Slip"}
              </Text>
            </Pressable>
          </View>

          {isAdmin && salary.status !== "paid" ? (
            <Pressable
              onPress={() => onMarkPaid(salary.id)}
              style={({ pressed }) => [
                styles.payButton,
                {
                  backgroundColor: colors.primary,
                  opacity: pressed ? 0.85 : 1,
                },
              ]}
            >
              <Ionicons name="cash-outline" size={15} color="#FFFFFF" />
              <Text style={styles.payButtonText}>Mark As Paid</Text>
            </Pressable>
          ) : null}
        </Animated.View>
      )}

      <View style={styles.expandIndicator}>
        <Ionicons name={expanded ? "chevron-up" : "chevron-down"} size={16} color={colors.textTertiary} />
      </View>
    </Pressable>
  );
}

function BreakdownRow({
  label,
  value,
  colors,
  bold,
}: {
  label: string;
  value: number;
  colors: typeof Colors.light;
  bold?: boolean;
}) {
  return (
    <View style={styles.breakdownRow}>
      <Text style={[styles.breakdownLabel, { color: colors.textSecondary, fontFamily: bold ? "Inter_600SemiBold" : "Inter_400Regular" }]}>
        {label}
      </Text>
      <Text style={[styles.breakdownValue, { color: colors.text, fontFamily: bold ? "Inter_600SemiBold" : "Inter_400Regular" }]}>
        INR {value.toLocaleString()}
      </Text>
    </View>
  );
}

function SalarySlipModal({
  visible,
  salary,
  colors,
  companyName,
  printing,
  onClose,
  onPrint,
}: {
  visible: boolean;
  salary: SalaryRecord | null;
  colors: typeof Colors.light;
  companyName: string;
  printing: boolean;
  onClose: () => void;
  onPrint: () => void;
}) {
  if (!salary) return null;

  const monthLabel = formatMonthLabel(salary.month);
  const statusColor =
    salary.status === "paid" ? colors.success :
    salary.status === "approved" ? colors.primary : colors.warning;

  return (
    <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}>
      <View style={[styles.modalBackdrop, { backgroundColor: "rgba(0, 0, 0, 0.45)" }]}>
        <View style={[styles.modalCard, { backgroundColor: colors.background, borderColor: colors.border }]}>
          <View style={styles.modalHeader}>
            <Text style={[styles.modalTitle, { color: colors.text, fontFamily: "Inter_700Bold" }]}>
              Salary Slip
            </Text>
            <Pressable onPress={onClose} hitSlop={10}>
              <Ionicons name="close" size={22} color={colors.textSecondary} />
            </Pressable>
          </View>

          <ScrollView
            contentContainerStyle={styles.modalContent}
            showsVerticalScrollIndicator={false}
          >
            <View style={[styles.slipTopCard, { borderColor: colors.border, backgroundColor: colors.backgroundElevated }]}>
              <View style={styles.slipTopHead}>
                <View style={{ flex: 1 }}>
                  <Text style={[styles.slipCompany, { color: colors.text, fontFamily: "Inter_700Bold" }]}>
                    {companyName}
                  </Text>
                  <Text style={[styles.slipSubtext, { color: colors.textSecondary, fontFamily: "Inter_400Regular" }]}>
                    {monthLabel}
                  </Text>
                </View>
                <View style={[styles.statusChip, { backgroundColor: statusColor + "15" }]}>
                  <Text style={[styles.statusText, { color: statusColor, fontFamily: "Inter_500Medium" }]}>
                    {salary.status}
                  </Text>
                </View>
              </View>
              <Text style={[styles.slipMeta, { color: colors.textSecondary, fontFamily: "Inter_500Medium" }]}>
                Slip No: {getSalarySlipNumber(salary)}
              </Text>
              <Text style={[styles.slipMeta, { color: colors.textSecondary, fontFamily: "Inter_500Medium" }]}>
                Employee: {salary.employeeName}
              </Text>
              <Text style={[styles.slipMeta, { color: colors.textSecondary, fontFamily: "Inter_500Medium" }]}>
                Generated: {new Date().toLocaleString()}
              </Text>
            </View>

            <View style={[styles.slipSection, { borderColor: colors.border, backgroundColor: colors.backgroundElevated }]}>
              <Text style={[styles.slipSectionTitle, { color: colors.success, fontFamily: "Inter_600SemiBold" }]}>
                Earnings
              </Text>
              <BreakdownRow label="Basic" value={salary.basic} colors={colors} />
              <BreakdownRow label="HRA" value={salary.hra} colors={colors} />
              <BreakdownRow label="Transport" value={salary.transport} colors={colors} />
              <BreakdownRow label="Medical" value={salary.medical} colors={colors} />
              <BreakdownRow label="Bonus" value={salary.bonus} colors={colors} />
              <BreakdownRow label="Overtime" value={salary.overtime} colors={colors} />
              <BreakdownRow label="Gross Pay" value={salary.grossPay} colors={colors} bold />
            </View>

            <View style={[styles.slipSection, { borderColor: colors.border, backgroundColor: colors.backgroundElevated }]}>
              <Text style={[styles.slipSectionTitle, { color: colors.danger, fontFamily: "Inter_600SemiBold" }]}>
                Deductions
              </Text>
              <BreakdownRow label="Income Tax" value={salary.tax} colors={colors} />
              <BreakdownRow label="Provident Fund" value={salary.pf} colors={colors} />
              <BreakdownRow label="Insurance" value={salary.insurance} colors={colors} />
              <BreakdownRow label="Total Deductions" value={salary.totalDeductions} colors={colors} bold />
            </View>

            <View style={[styles.slipNetCard, { borderColor: colors.success + "45", backgroundColor: colors.success + "10" }]}>
              <Text style={[styles.slipNetLabel, { color: colors.text, fontFamily: "Inter_700Bold" }]}>
                Net Pay
              </Text>
              <Text style={[styles.slipNetValue, { color: colors.success, fontFamily: "Inter_700Bold" }]}>
                {formatCurrency(salary.netPay)}
              </Text>
            </View>
          </ScrollView>

          <View style={styles.modalFooter}>
            <Pressable
              onPress={onClose}
              style={({ pressed }) => [
                styles.modalFooterButton,
                {
                  borderColor: colors.border,
                  backgroundColor: colors.surface,
                  opacity: pressed ? 0.86 : 1,
                },
              ]}
            >
              <Text style={[styles.modalFooterButtonText, { color: colors.textSecondary, fontFamily: "Inter_600SemiBold" }]}>
                Close
              </Text>
            </Pressable>
            <Pressable
              onPress={onPrint}
              disabled={printing}
              style={({ pressed }) => [
                styles.modalFooterButton,
                {
                  borderColor: colors.primary,
                  backgroundColor: colors.primary,
                  opacity: pressed || printing ? 0.85 : 1,
                },
              ]}
            >
              {printing ? (
                <ActivityIndicator size="small" color="#FFFFFF" />
              ) : (
                <Ionicons name="print-outline" size={16} color="#FFFFFF" />
              )}
              <Text style={[styles.modalFooterButtonText, { color: "#FFFFFF", fontFamily: "Inter_600SemiBold" }]}>
                {printing ? "Printing..." : "Print Slip"}
              </Text>
            </Pressable>
          </View>
        </View>
      </View>
    </Modal>
  );
}

export default function SalaryScreen() {
  const { user } = useAuth();
  const insets = useSafeAreaInsets();
  const { colors } = useAppTheme();
  const [salaries, setSalaries] = useState<SalaryRecord[]>([]);
  const [selectedSlip, setSelectedSlip] = useState<SalaryRecord | null>(null);
  const [printingSlipId, setPrintingSlipId] = useState<string | null>(null);
  const isAdmin = user?.role === "admin";

  const loadData = useCallback(async () => {
    const [salaryData, employees] = await Promise.all([getSalaries(), getEmployees()]);
    if (!user) {
      setSalaries([]);
      return;
    }
    if (isAdmin) {
      setSalaries(salaryData);
      return;
    }

    const mappedEmployeeIds = new Set(
      employees
        .filter((employee) => employee.email === user.email || employee.name === user.name)
        .map((employee) => employee.id)
    );
    const filtered = salaryData.filter(
      (salary) =>
        salary.employeeId === user.id ||
        salary.employeeName === user.name ||
        mappedEmployeeIds.has(salary.employeeId)
    );
    setSalaries(filtered);
  }, [isAdmin, user]);

  useEffect(() => { loadData(); }, [loadData]);

  const handleMarkPaid = useCallback(
    async (salaryId: string) => {
      if (!isAdmin || !user) return;
      await updateSalaryStatus(salaryId, "paid");
      const target = salaries.find((entry) => entry.id === salaryId);
      await addAuditLog({
        id: Crypto.randomUUID(),
        userId: user.id,
        userName: user.name,
        action: "Salary Paid",
        details: `Marked salary as paid for ${target?.employeeName || "employee"}`,
        timestamp: new Date().toISOString(),
        module: "Salary",
      });
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      await loadData();
    },
    [isAdmin, loadData, salaries, user]
  );

  const handleMarkAllPaid = useCallback(async () => {
    if (!isAdmin || !user) return;
    const pending = salaries.filter((salary) => salary.status !== "paid");
    if (!pending.length) return;
    for (const salary of pending) {
      await updateSalaryStatus(salary.id, "paid");
    }
    await addAuditLog({
      id: Crypto.randomUUID(),
      userId: user.id,
      userName: user.name,
      action: "Bulk Salary Paid",
      details: `Marked ${pending.length} salary records as paid`,
      timestamp: new Date().toISOString(),
      module: "Salary",
    });
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    await loadData();
  }, [isAdmin, loadData, salaries, user]);

  const handleViewSlip = useCallback((salary: SalaryRecord) => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    setSelectedSlip(salary);
  }, []);

  const handleCloseSlip = useCallback(() => {
    setSelectedSlip(null);
  }, []);

  const handlePrintSlip = useCallback(
    async (salary: SalaryRecord) => {
      const companyName = user?.companyName || "Lumina FieldForce";
      setPrintingSlipId(salary.id);
      try {
        const html = buildSalarySlipHtml({
          salary,
          companyName,
          generatedBy: user?.name || "Payroll Admin",
          generatedAtISO: new Date().toISOString(),
        });
        await Print.printAsync({ html });
        Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unable to print salary slip.";
        Alert.alert("Print Failed", message);
      } finally {
        setPrintingSlipId((current) => (current === salary.id ? null : current));
      }
    },
    [user?.companyName, user?.name]
  );

  return (
    <AppCanvas>
      <FlatList
        data={salaries}
        keyExtractor={(item) => item.id}
        contentContainerStyle={[styles.listContent, { paddingTop: insets.top + 16 }]}
        showsVerticalScrollIndicator={false}
        ListHeaderComponent={
          <View style={styles.headerRow}>
            <Pressable onPress={() => router.back()} hitSlop={12}>
              <Ionicons name="arrow-back" size={24} color={colors.text} />
            </Pressable>
            <Text style={[styles.headerTitle, { color: colors.text, fontFamily: "Inter_700Bold" }]}>Salary</Text>
            {isAdmin ? (
              <Pressable onPress={() => void handleMarkAllPaid()} hitSlop={10}>
                <Ionicons name="cash-outline" size={23} color={colors.primary} />
              </Pressable>
            ) : (
              <View style={{ width: 24 }} />
            )}
          </View>
        }
        renderItem={({ item }) => (
          <SalaryBreakdown
            salary={item}
            colors={colors}
            isAdmin={isAdmin}
            onMarkPaid={handleMarkPaid}
            onViewSlip={handleViewSlip}
            onPrintSlip={(salary) => void handlePrintSlip(salary)}
            printingSlipId={printingSlipId}
          />
        )}
        ListEmptyComponent={
          <View style={[styles.emptyState, { backgroundColor: colors.backgroundElevated, borderColor: colors.border }]}>
            <Ionicons name="wallet-outline" size={40} color={colors.textTertiary} />
            <Text style={[styles.emptyText, { color: colors.textSecondary }]}>
              {isAdmin ? "No salary records" : "No salary record for your profile"}
            </Text>
          </View>
        }
      />

      <SalarySlipModal
        visible={Boolean(selectedSlip)}
        salary={selectedSlip}
        colors={colors}
        companyName={user?.companyName || "Lumina FieldForce"}
        printing={selectedSlip ? printingSlipId === selectedSlip.id : false}
        onClose={handleCloseSlip}
        onPrint={() => {
          if (!selectedSlip) return;
          void handlePrintSlip(selectedSlip);
        }}
      />
    </AppCanvas>
  );
}

const styles = StyleSheet.create({
  listContent: { paddingHorizontal: 20, paddingBottom: 40, gap: 10 },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  headerTitle: { fontSize: 20, letterSpacing: -0.3 },
  salaryCard: { 
    borderRadius: 24, 
    padding: 20,
    borderWidth: 1,
    boxShadow: "0px 10px 26px rgba(10, 35, 62, 0.12)",
  },
  salaryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  salaryHeaderLeft: { flex: 1, gap: 2 },
  salaryName: { fontSize: 15 },
  salaryMonth: { fontSize: 12 },
  salaryHeaderRight: { alignItems: "flex-end", gap: 4 },
  netPay: { fontSize: 16 },
  statusChip: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  statusText: { fontSize: 10, textTransform: "capitalize" as const },
  breakdown: { marginTop: 12 },
  breakdownDivider: { height: 1, marginBottom: 12 },
  breakdownSection: { fontSize: 12, marginBottom: 8, textTransform: "uppercase" as const, letterSpacing: 0.5 },
  breakdownRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  breakdownLabel: { fontSize: 13 },
  breakdownValue: { fontSize: 13 },
  netPayRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
  },
  actionRow: {
    marginTop: 12,
    flexDirection: "row",
    gap: 8,
  },
  secondaryActionButton: {
    flex: 1,
    minHeight: 36,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 10,
  },
  secondaryActionButtonText: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  payButton: {
    marginTop: 12,
    minHeight: 38,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  payButtonText: {
    color: "#FFFFFF",
    fontSize: 12.5,
    fontFamily: "Inter_600SemiBold",
  },
  netPayLabel: { fontSize: 15 },
  netPayValue: { fontSize: 15 },
  expandIndicator: { alignItems: "center", marginTop: 8 },
  emptyState: {
    borderRadius: 16,
    padding: 40,
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
  },
  emptyText: { fontSize: 14, fontFamily: "Inter_400Regular" },
  modalBackdrop: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  modalCard: {
    maxHeight: "92%",
    borderRadius: 16,
    borderWidth: 1,
    overflow: "hidden",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(148, 163, 184, 0.45)",
  },
  modalTitle: {
    fontSize: 16,
    letterSpacing: -0.2,
  },
  modalContent: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 20,
    gap: 10,
  },
  slipTopCard: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    gap: 4,
  },
  slipTopHead: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 2,
  },
  slipCompany: {
    fontSize: 16,
  },
  slipSubtext: {
    fontSize: 12.5,
  },
  slipMeta: {
    fontSize: 12,
  },
  slipSection: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
  },
  slipSectionTitle: {
    fontSize: 12.5,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  slipNetCard: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  slipNetLabel: {
    fontSize: 14.5,
  },
  slipNetValue: {
    fontSize: 16,
  },
  modalFooter: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(148, 163, 184, 0.45)",
    flexDirection: "row",
    padding: 12,
    gap: 8,
  },
  modalFooterButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  modalFooterButtonText: {
    fontSize: 12.5,
  },
});
