import type {
  AppUser,
  Employee,
  AttendanceRecord,
  SalaryRecord,
  Task,
  Expense,
  Conversation,
  AuditLog,
  BranchInfo,
  Geofence,
  Team,
  AppNotification,
  SupportThread,
} from "./types";

export const DEFAULT_COMPANY_ID = "cmp_trackforce_ai";
export const DEFAULT_COMPANY_NAME = "TrackForce AI";

export const demoUsers: AppUser[] = [
  {
    id: "u1",
    name: "Rajesh Kumar",
    email: "admin@trackforce.ai",
    role: "admin",
    companyId: DEFAULT_COMPANY_ID,
    companyName: DEFAULT_COMPANY_NAME,
    department: "Management",
    branch: "Mumbai HQ",
    phone: "+91 98765 43210",
    joinDate: "2022-01-15",
  },
  {
    id: "u2",
    name: "Priya Sharma",
    email: "hr@trackforce.ai",
    role: "hr",
    companyId: DEFAULT_COMPANY_ID,
    companyName: DEFAULT_COMPANY_NAME,
    department: "Human Resources",
    branch: "Mumbai HQ",
    phone: "+91 98765 43211",
    joinDate: "2022-03-20",
  },
  {
    id: "u3",
    name: "Amit Patel",
    email: "manager@trackforce.ai",
    role: "manager",
    companyId: DEFAULT_COMPANY_ID,
    companyName: DEFAULT_COMPANY_NAME,
    department: "Sales",
    branch: "Delhi Branch",
    phone: "+91 98765 43212",
    joinDate: "2022-06-10",
  },
  {
    id: "u4",
    name: "Sneha Reddy",
    email: "sales@trackforce.ai",
    role: "salesperson",
    companyId: DEFAULT_COMPANY_ID,
    companyName: DEFAULT_COMPANY_NAME,
    department: "Sales",
    branch: "Bangalore Branch",
    phone: "+91 98765 43213",
    joinDate: "2023-01-05",
  },
  {
    id: "u5",
    name: "Dhruv Shah",
    email: "ahmedabad@trackforce.ai",
    role: "salesperson",
    companyId: DEFAULT_COMPANY_ID,
    companyName: DEFAULT_COMPANY_NAME,
    department: "Sales",
    branch: "Ahmedabad - Mahakant Complex",
    phone: "+91 98765 43220",
    joinDate: "2024-01-12",
  },
];

export const demoPasswords: Record<string, string> = {
  "admin@trackforce.ai": "admin123",
  "hr@trackforce.ai": "hr123",
  "manager@trackforce.ai": "manager123",
  "sales@trackforce.ai": "sales123",
  "ahmedabad@trackforce.ai": "ahmed123",
};

export const demoEmployees: Employee[] = [
  {
    id: "e1",
    companyId: DEFAULT_COMPANY_ID,
    name: "Rajesh Kumar",
    role: "admin",
    department: "Management",
    status: "active",
    email: "admin@trackforce.ai",
    phone: "+91 98765 43210",
    branch: "Mumbai HQ",
    joinDate: "2022-01-15",
  },
  {
    id: "e2",
    companyId: DEFAULT_COMPANY_ID,
    name: "Priya Sharma",
    role: "hr",
    department: "Human Resources",
    status: "active",
    email: "hr@trackforce.ai",
    phone: "+91 98765 43211",
    branch: "Mumbai HQ",
    joinDate: "2022-03-20",
  },
  {
    id: "e3",
    companyId: DEFAULT_COMPANY_ID,
    name: "Amit Patel",
    role: "manager",
    department: "Sales",
    status: "active",
    email: "manager@trackforce.ai",
    phone: "+91 98765 43212",
    branch: "Delhi Branch",
    joinDate: "2022-06-10",
  },
  {
    id: "e4",
    companyId: DEFAULT_COMPANY_ID,
    name: "Sneha Reddy",
    role: "salesperson",
    department: "Sales",
    status: "active",
    email: "sales@trackforce.ai",
    phone: "+91 98765 43213",
    branch: "Bangalore Branch",
    joinDate: "2023-01-05",
  },
  {
    id: "e5",
    companyId: DEFAULT_COMPANY_ID,
    name: "Vikram Singh",
    role: "salesperson",
    department: "Sales",
    status: "idle",
    email: "vikram@trackforce.ai",
    phone: "+91 98765 43214",
    branch: "Delhi Branch",
    joinDate: "2023-02-14",
  },
  {
    id: "e6",
    companyId: DEFAULT_COMPANY_ID,
    name: "Ananya Gupta",
    role: "salesperson",
    department: "Sales",
    status: "offline",
    email: "ananya@trackforce.ai",
    phone: "+91 98765 43215",
    branch: "Mumbai HQ",
    joinDate: "2023-04-01",
  },
  {
    id: "e7",
    companyId: DEFAULT_COMPANY_ID,
    name: "Karthik Nair",
    role: "salesperson",
    department: "Sales",
    status: "active",
    email: "karthik@trackforce.ai",
    phone: "+91 98765 43216",
    branch: "Bangalore Branch",
    joinDate: "2023-05-20",
  },
  {
    id: "e8",
    companyId: DEFAULT_COMPANY_ID,
    name: "Meera Joshi",
    role: "hr",
    department: "Human Resources",
    status: "active",
    email: "meera@trackforce.ai",
    phone: "+91 98765 43217",
    branch: "Delhi Branch",
    joinDate: "2023-06-15",
  },
  {
    id: "e9",
    companyId: DEFAULT_COMPANY_ID,
    name: "Rohit Verma",
    role: "salesperson",
    department: "Sales",
    status: "idle",
    email: "rohit@trackforce.ai",
    phone: "+91 98765 43218",
    branch: "Mumbai HQ",
    joinDate: "2023-08-10",
  },
  {
    id: "e10",
    companyId: DEFAULT_COMPANY_ID,
    name: "Deepa Iyer",
    role: "manager",
    department: "Operations",
    status: "active",
    email: "deepa@trackforce.ai",
    phone: "+91 98765 43219",
    branch: "Bangalore Branch",
    joinDate: "2023-09-01",
  },
  {
    id: "e11",
    companyId: DEFAULT_COMPANY_ID,
    name: "Dhruv Shah",
    role: "salesperson",
    department: "Sales",
    status: "active",
    email: "ahmedabad@trackforce.ai",
    phone: "+91 98765 43220",
    branch: "Ahmedabad - Mahakant Complex",
    joinDate: "2024-01-12",
  },
];

const today = new Date().toISOString().split("T")[0];
const seedNow = new Date().toISOString();
const MAHAKANT_LAT = 23.0252;
const MAHAKANT_LNG = 72.5713;
const MAHAKANT_ADDRESS = "Mahakant Complex, Paldi, Ashram Road, Ahmedabad, Gujarat, India";
const MAHAKANT_BRANCH = "Ahmedabad - Mahakant Complex";

export const demoAttendance: AttendanceRecord[] = [
  { id: "a1", userId: "e1", userName: "Rajesh Kumar", type: "checkin", timestamp: `${today}T09:02:00`, location: { lat: 19.076, lng: 72.8777 } },
  { id: "a2", userId: "e2", userName: "Priya Sharma", type: "checkin", timestamp: `${today}T08:55:00`, location: { lat: 19.076, lng: 72.8777 } },
  { id: "a3", userId: "e3", userName: "Amit Patel", type: "checkin", timestamp: `${today}T09:15:00`, location: { lat: 28.6139, lng: 77.209 } },
  { id: "a4", userId: "e4", userName: "Sneha Reddy", type: "checkin", timestamp: `${today}T08:45:00`, location: { lat: 12.9716, lng: 77.5946 } },
  { id: "a5", userId: "e5", userName: "Vikram Singh", type: "checkin", timestamp: `${today}T09:30:00`, location: { lat: 28.6139, lng: 77.209 } },
  { id: "a6", userId: "e7", userName: "Karthik Nair", type: "checkin", timestamp: `${today}T08:50:00`, location: { lat: 12.9716, lng: 77.5946 } },
  { id: "a7", userId: "e8", userName: "Meera Joshi", type: "checkin", timestamp: `${today}T09:05:00`, location: { lat: 28.6139, lng: 77.209 } },
  { id: "a8", userId: "e10", userName: "Deepa Iyer", type: "checkin", timestamp: `${today}T08:58:00`, location: { lat: 12.9716, lng: 77.5946 } },
  { id: "a9", userId: "e11", userName: "Dhruv Shah", type: "checkin", timestamp: `${today}T09:12:00`, location: { lat: MAHAKANT_LAT, lng: MAHAKANT_LNG } },
];

export const demoSalaries: SalaryRecord[] = [
  {
    id: "s1", employeeId: "e1", employeeName: "Rajesh Kumar", month: "2026-01",
    basic: 85000, hra: 34000, transport: 5000, medical: 3000, bonus: 15000, overtime: 0,
    tax: 14200, pf: 10200, insurance: 2000,
    grossPay: 142000, totalDeductions: 26400, netPay: 115600, status: "paid",
  },
  {
    id: "s2", employeeId: "e4", employeeName: "Sneha Reddy", month: "2026-01",
    basic: 45000, hra: 18000, transport: 3000, medical: 2000, bonus: 8000, overtime: 4500,
    tax: 8050, pf: 5400, insurance: 1500,
    grossPay: 80500, totalDeductions: 14950, netPay: 65550, status: "paid",
  },
  {
    id: "s3", employeeId: "e3", employeeName: "Amit Patel", month: "2026-01",
    basic: 65000, hra: 26000, transport: 4000, medical: 2500, bonus: 10000, overtime: 0,
    tax: 10750, pf: 7800, insurance: 1800,
    grossPay: 107500, totalDeductions: 20350, netPay: 87150, status: "approved",
  },
  {
    id: "s4", employeeId: "e2", employeeName: "Priya Sharma", month: "2026-01",
    basic: 55000, hra: 22000, transport: 3500, medical: 2500, bonus: 5000, overtime: 0,
    tax: 8800, pf: 6600, insurance: 1600,
    grossPay: 88000, totalDeductions: 17000, netPay: 71000, status: "pending",
  },
];

export const demoTasks: Task[] = [
  {
    id: "t1", title: "Client meeting - Infosys",
    description: "Prepare presentation and visit Infosys campus for product demo",
    assignedTo: "e4", assignedToName: "Sneha Reddy",
    assignedBy: "e3", teamId: "tm1", teamName: "North & South Enterprise Sales", status: "in_progress", priority: "high",
    dueDate: "2026-02-20", createdAt: "2026-02-15",
  },
  {
    id: "t2", title: "Submit monthly report",
    description: "Compile and submit the January sales report with all metrics",
    assignedTo: "e5", assignedToName: "Vikram Singh",
    assignedBy: "e3", teamId: "tm1", teamName: "North & South Enterprise Sales", status: "pending", priority: "medium",
    dueDate: "2026-02-22", createdAt: "2026-02-14",
  },
  {
    id: "t3", title: "Follow up with TCS lead",
    description: "Call the procurement team at TCS regarding pending PO",
    assignedTo: "e7", assignedToName: "Karthik Nair",
    assignedBy: "e3", teamId: "tm1", teamName: "North & South Enterprise Sales", status: "completed", priority: "high",
    dueDate: "2026-02-18", createdAt: "2026-02-12",
  },
  {
    id: "t4", title: "Onboard new salesperson",
    description: "Complete onboarding documentation and system access for new hire",
    assignedTo: "e2", assignedToName: "Priya Sharma",
    assignedBy: "e1", status: "in_progress", priority: "medium",
    dueDate: "2026-02-25", createdAt: "2026-02-16",
  },
  {
    id: "t5", title: "Update CRM entries",
    description: "Update all Q4 client interactions in the CRM system",
    assignedTo: "e9", assignedToName: "Rohit Verma",
    assignedBy: "e3", teamId: "tm1", teamName: "North & South Enterprise Sales", status: "pending", priority: "low",
    dueDate: "2026-02-28", createdAt: "2026-02-17",
  },
];

export const demoTeams: Team[] = [
  {
    id: "tm1",
    name: "North & South Enterprise Sales",
    ownerId: "u3",
    ownerName: "Amit Patel",
    memberIds: ["e4", "e5", "e7", "e9", "e11"],
    createdAt: seedNow,
    updatedAt: seedNow,
  },
  {
    id: "tm2",
    name: "HR Operations Core",
    ownerId: "u2",
    ownerName: "Priya Sharma",
    memberIds: ["e2", "e8"],
    createdAt: seedNow,
    updatedAt: seedNow,
  },
];

export const demoExpenses: Expense[] = [
  { id: "x1", userId: "e4", userName: "Sneha Reddy", category: "Travel", amount: 4500, description: "Cab to Infosys campus - client meeting", status: "approved", date: "2026-02-15" },
  { id: "x2", userId: "e5", userName: "Vikram Singh", category: "Meals", amount: 1200, description: "Client lunch - Wipro team", status: "pending", date: "2026-02-16" },
  { id: "x3", userId: "e7", userName: "Karthik Nair", category: "Travel", amount: 8500, description: "Flight tickets Delhi-Bangalore", status: "approved", date: "2026-02-14" },
  { id: "x4", userId: "e9", userName: "Rohit Verma", category: "Office Supplies", amount: 2300, description: "Presentation materials and printing", status: "rejected", date: "2026-02-13" },
  { id: "x5", userId: "e3", userName: "Amit Patel", category: "Accommodation", amount: 6000, description: "Hotel stay - Mumbai visit", status: "pending", date: "2026-02-17" },
];

export const demoConversations: Conversation[] = [
  {
    id: "c1", salespersonId: "e4", salespersonName: "Sneha Reddy",
    customerName: "Infosys - Procurement Team", date: "2026-02-15", duration: "32:15",
    interestScore: 82, pitchScore: 88, confidenceScore: 91, talkListenRatio: 45,
    sentiment: "positive", buyingIntent: "high",
    objections: ["Budget constraints for Q1", "Need board approval for large purchases"],
    improvements: ["Could have addressed ROI earlier", "Consider shorter pitch duration"],
    summary: "Excellent meeting with Infosys procurement. Strong interest in enterprise package. Customer showed high buying intent but needs internal approval. Follow-up scheduled for next week.",
    keyPhrases: ["enterprise solution", "ROI timeline", "implementation support", "annual contract"],
  },
  {
    id: "c2", salespersonId: "e5", salespersonName: "Vikram Singh",
    customerName: "Wipro - IT Services", date: "2026-02-14", duration: "18:42",
    interestScore: 55, pitchScore: 62, confidenceScore: 58, talkListenRatio: 68,
    sentiment: "neutral", buyingIntent: "medium",
    objections: ["Already using competitor product", "Contract renewal not until Q3"],
    improvements: ["Talk less, listen more", "Ask more discovery questions", "Address competitor comparison proactively"],
    summary: "Initial exploratory call with Wipro. Customer is currently using a competitor but open to evaluating alternatives when contract comes up for renewal.",
    keyPhrases: ["competitor comparison", "contract renewal", "feature gap", "pricing flexibility"],
  },
  {
    id: "c3", salespersonId: "e7", salespersonName: "Karthik Nair",
    customerName: "TCS - Digital Division", date: "2026-02-13", duration: "45:30",
    interestScore: 94, pitchScore: 92, confidenceScore: 95, talkListenRatio: 40,
    sentiment: "positive", buyingIntent: "high",
    objections: ["Integration with existing SAP system"],
    improvements: ["Excellent performance overall", "Could provide more case studies"],
    summary: "Outstanding call with TCS. Customer is very enthusiastic about our platform. PO expected within 2 weeks. Integration requirements discussed in detail.",
    keyPhrases: ["SAP integration", "enterprise deployment", "scalability", "dedicated support"],
  },
  {
    id: "c4", salespersonId: "e9", salespersonName: "Rohit Verma",
    customerName: "HCL Technologies", date: "2026-02-12", duration: "22:08",
    interestScore: 35, pitchScore: 45, confidenceScore: 42, talkListenRatio: 72,
    sentiment: "negative", buyingIntent: "low",
    objections: ["Price too high", "Not a priority right now", "Need to see more references"],
    improvements: ["Improve pitch structure", "Reduce talking time", "Practice handling price objections", "Use more social proof"],
    summary: "Challenging call. Customer not convinced of value proposition. Needs significant nurturing. Consider different approach for follow-up.",
    keyPhrases: ["pricing concern", "budget freeze", "not a priority", "reference customers"],
  },
];

export const demoAuditLogs: AuditLog[] = [
  { id: "al1", userId: "e1", userName: "Rajesh Kumar", action: "User Login", details: "Admin logged in from Mumbai HQ", timestamp: `${today}T09:02:00`, module: "Auth" },
  { id: "al2", userId: "e4", userName: "Sneha Reddy", action: "Check In", details: "Checked in at Bangalore Branch", timestamp: `${today}T08:45:00`, module: "Attendance" },
  { id: "al3", userId: "e1", userName: "Rajesh Kumar", action: "Expense Approved", details: "Approved travel expense for Sneha Reddy - INR 4,500", timestamp: `${today}T10:15:00`, module: "Expenses" },
  { id: "al4", userId: "e3", userName: "Amit Patel", action: "Task Created", details: "Assigned 'Client meeting - Infosys' to Sneha Reddy", timestamp: `${today}T10:30:00`, module: "Tasks" },
  { id: "al5", userId: "e2", userName: "Priya Sharma", action: "Salary Generated", details: "Generated January salary slips for all employees", timestamp: `${today}T11:00:00`, module: "Salary" },
  { id: "al6", userId: "e7", userName: "Karthik Nair", action: "Recording Uploaded", details: "Uploaded conversation recording with TCS", timestamp: `${today}T14:30:00`, module: "Sales AI" },
  { id: "al7", userId: "e1", userName: "Rajesh Kumar", action: "Settings Updated", details: "Updated company branding colors", timestamp: `${today}T15:00:00`, module: "Settings" },
  { id: "al8", userId: "e3", userName: "Amit Patel", action: "Report Exported", details: "Exported weekly attendance report as PDF", timestamp: `${today}T16:00:00`, module: "Reports" },
  { id: "al9", userId: "e11", userName: "Dhruv Shah", action: "Check In", details: "Checked in at Mahakant Complex, Paldi, Ahmedabad", timestamp: `${today}T09:12:00`, module: "Attendance" },
];

export const demoBranches: BranchInfo[] = [
  { id: "b1", name: "Mumbai HQ", address: "Bandra Kurla Complex, Mumbai", employeeCount: 4 },
  { id: "b2", name: "Delhi Branch", address: "Connaught Place, New Delhi", employeeCount: 3 },
  { id: "b3", name: "Bangalore Branch", address: "Koramangala, Bangalore", employeeCount: 3 },
  { id: "b4", name: MAHAKANT_BRANCH, address: MAHAKANT_ADDRESS, employeeCount: 1 },
];

export const demoGeofences: Geofence[] = [
  {
    id: "g1",
    name: "Mumbai HQ Office",
    radiusMeters: 300,
    latitude: 19.076,
    longitude: 72.8777,
    assignedEmployeeIds: ["u1", "u2", "e1", "e2", "e9"],
    isActive: true,
    allowOverride: false,
    workingHoursStart: "08:30",
    workingHoursEnd: "19:30",
    createdAt: seedNow,
    updatedAt: seedNow,
  },
  {
    id: "g2",
    name: "Delhi Branch Office",
    radiusMeters: 280,
    latitude: 28.6139,
    longitude: 77.209,
    assignedEmployeeIds: ["u3", "e3", "e5", "e8"],
    isActive: true,
    allowOverride: false,
    workingHoursStart: "08:00",
    workingHoursEnd: "19:00",
    createdAt: seedNow,
    updatedAt: seedNow,
  },
  {
    id: "g3",
    name: "Bangalore Branch Office",
    radiusMeters: 320,
    latitude: 12.9716,
    longitude: 77.5946,
    assignedEmployeeIds: ["u4", "e4", "e7", "e10"],
    isActive: true,
    allowOverride: true,
    workingHoursStart: "08:00",
    workingHoursEnd: "20:00",
    createdAt: seedNow,
    updatedAt: seedNow,
  },
  {
    id: "g4",
    name: MAHAKANT_BRANCH,
    radiusMeters: 800,
    latitude: MAHAKANT_LAT,
    longitude: MAHAKANT_LNG,
    assignedEmployeeIds: ["u5", "e11"],
    isActive: true,
    allowOverride: false,
    workingHoursStart: "08:30",
    workingHoursEnd: "19:30",
    createdAt: seedNow,
    updatedAt: seedNow,
  },
];

export const demoNotifications: AppNotification[] = [
  {
    id: "n1",
    title: "Quarterly Sales Kickoff",
    body: "All sales teams join the kickoff at 10:00 AM in the main conference room.",
    kind: "announcement",
    audience: "salesperson",
    createdById: "e1",
    createdByName: "Rajesh Kumar",
    createdAt: `${today}T08:00:00`,
    readByIds: ["e4"],
  },
  {
    id: "n2",
    title: "Attendance Policy Reminder",
    body: "All employees must complete geo-verified check-in before 10:30 AM.",
    kind: "policy",
    audience: "all",
    createdById: "e2",
    createdByName: "Priya Sharma",
    createdAt: `${today}T08:30:00`,
    readByIds: ["e1", "e2", "e3"],
  },
  {
    id: "n3",
    title: "Server Maintenance Window",
    body: "Backend maintenance is scheduled tonight from 11:30 PM to 12:30 AM.",
    kind: "alert",
    audience: "all",
    createdById: "e1",
    createdByName: "Rajesh Kumar",
    createdAt: `${today}T12:15:00`,
    readByIds: [],
  },
];

export const demoSupportThreads: SupportThread[] = [
  {
    id: "s1",
    subject: "Unable to upload expense receipt",
    requestedById: "e4",
    requestedByName: "Sneha Reddy",
    requestedByRole: "salesperson",
    status: "open",
    priority: "normal",
    createdAt: `${today}T10:05:00`,
    updatedAt: `${today}T10:40:00`,
    messages: [
      {
        id: "sm1",
        senderId: "e4",
        senderName: "Sneha Reddy",
        senderRole: "salesperson",
        message: "Expense form saves but receipt upload keeps failing on mobile data.",
        createdAt: `${today}T10:05:00`,
      },
      {
        id: "sm2",
        senderId: "e3",
        senderName: "Amit Patel",
        senderRole: "manager",
        message: "Please retry on Wi-Fi once. If it still fails, share screenshot here.",
        createdAt: `${today}T10:40:00`,
      },
    ],
  },
];
